### ISSUE TITLE
Bump @actions/core to latest

### ISSUE THREAD

**Issue by ashwin153** [totallymoney/assign-reviewers-by-labels-action#135]
I get the following warning when I use this action.

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

I think upgrading to the latest version of @actions/core (1.10.0) will fix this warning.

https://github.com/totallymoney/assign-reviewers-by-labels-action/pull/104

Could this pull request be merged?

**Comment by ljbc1994** [comment]
Thanks @ashwin153 for reporting -- should be resolved in latest version
