### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by scottrmercer** [totallymoney/assign-reviewers-by-labels-action#60]
I'm having an issue in which the workflow is not able to find the config file. I have placed the config file in .github and named it the using the default value.  I also tried explicitly setting the path to the config file in the workflow, yielding the same result. 

My workflow: 
`name: "Auto Assign Reviewers"
on:
  pull_request:
    types:
      - unlabeled
      - labeled

jobs:
  assign_and_unassign:
    name: assign and unassign reviewers
    runs-on: ubuntu-latest
    steps:
      - name: main
        id: assign-reviewers
        uses: totallymoney/assign-reviewers-by-labels-action@v1.1
        with:          
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
`

My config file (in project):
![image](https://user-images.githubusercontent.com/1252889/191807234-81f00101-a1c3-49c1-a3cb-342c70dc2241.png)

Debug Output:
`##[debug]Evaluating condition for step: 'main'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: main
##[debug]Loading inputs
##[debug]Evaluating: secrets.GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run totallymoney/assign-reviewers-by-labels-action@v1.1
  with:
    config-file: .github/assign_label_reviewers.yml
    repo-token: ***
    unassign-if-label-removed: true
##[debug]📄 Retrieving config from yaml file...
Error: Failed to load configuration 7dd6[3](https://github.com/everwise/integration-service/actions/runs/3107132237/jobs/5035150668#step:2:3)f[7](https://github.com/everwise/integration-service/actions/runs/3107132237/jobs/5035150668#step:2:7) Not Found .github/assign_label_reviewers.yml
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: main`

Thank you!

**Comment by ljbc1994** [comment]
Hey @scottrmercer 

First of all, thanks for giving the action a go!

Has this been run from a branch? 

The config file will need to be on the main branch as the action is looking at the main branch for the config file. Then, it will work when you're doing PRs.

**Comment by scottrmercer** [comment]
Ah - that was it. Thanks for the fast response, and thanks for creating this action!
